### ISSUE TITLE
Is dit niet gewoon een lijst?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Abeeryu/the-startup-responsive-interactieve-website#1]
Een `<ul>` lijst met feiten over De Voorhoede. (Of een `<dl>` lijst als je jezelf uit wilt dagen.)

https://github.com/Abeeryu/the-startup-responsive-interactieve-website/blob/14310c03840130a051ce0008a176395595e0e63f/index.html#L54-L100

**Comment by Abeeryu** [comment]
Dankjewel voor je feedback! Ik heb hier een ul gebruikt, en volgende keer ga ik de andere dl wel proberen! :)
![Screenshot 2024-01-17 114248](https://github.com/Abeeryu/the-startup-responsive-interactieve-website/assets/144008500/ce269ef9-f85a-4737-8e5e-1ce6198d6223)
