### ISSUE TITLE
Veel onnodige breakpoints in je tekst

### ISSUE THREAD

**Issue by Ryank2004** [Abeeryu/the-startup-responsive-interactieve-website#14]
Je maakt veel gebruik van <br> om je tekst op te delen. Dit is niet nodig als je de container de juiste styling geeft. Dan word je tekst ook responsive.

**Comment by Abeeryu** [comment]
Dankjewel voor je feedback. Het was handig, en ik heb het wel toegepast! :)
![Screenshot 2024-01-17 113455](https://github.com/Abeeryu/the-startup-responsive-interactieve-website/assets/144008500/768e0c42-03c9-4497-8a5d-b48169f61ebd)
