### ISSUE TITLE
Regeleindes in je tekst

### ISSUE THREAD

**Issue by KrijnHoetmer** [Abeeryu/the-startup-responsive-interactieve-website#2]
Probeer `<br>` niet te gebruiken (behalve als je gedichten of adressen schrijft). In alle andere gevallen wil je de stijl met CSS bepalen, bijvoorbeeld met `margin` of `max-width`.

https://github.com/Abeeryu/the-startup-responsive-interactieve-website/blob/14310c03840130a051ce0008a176395595e0e63f/index.html#L134-L139

**Comment by Abeeryu** [comment]
Thanks! ik heb het toegepast!

![Screenshot 2024-01-18 000345](https://github.com/Abeeryu/the-startup-responsive-interactieve-website/assets/144008500/c3db11d9-8812-46a3-b8c8-edb8ad61d2c7)
