### ISSUE TITLE
Responsive maken met margins

### ISSUE THREAD

**Issue by Marwaxhello** [Abeeryu/the-startup-responsive-interactieve-website#3]
Probeer het gebruik van margins te verminderen. In plaats daarvan is het wellicht effectiever om elementen te centreren door ze naar links of rechts uit te lijnen en vervolgens padding toe te voegen.

Bijvoorbeeld, het instellen van `margin-left: 112px;` kan problematisch zijn bij het creëren van een responsieve website. Overweeg in plaats daarvan om het element links te centreren door gebruik te maken van een combinatie van `margin: 0 auto;` voor het centreren en `padding` voor de gewenste ruimte rondom het element. Dit maakt je lay-out flexibeler en past zich beter aan verschillende schermformaten aan.

**Comment by Marwaxhello** [comment]
Het lijkt erop dat de mobiele versie van je website iets uitsteekt, en ik vermoed dat dit te wijten is aan de eerder genoemde marges. Dit kan je fixen net als geadviseert.

**Comment by Abeeryu** [comment]
Gedaan!
