### ISSUE TITLE
Witruimte

### ISSUE THREAD

**Issue by Marwaxhello** [Abeeryu/the-startup-responsive-interactieve-website#4]
Ik merk op dat er weinig witruimte is in de header en footer van je website, wat de gebruikerservaring onrustig kan maken. Overweeg het toevoegen van witruimte door een `padding-top` toe te voegen, vooral in de header en `padding-bottom` in de footer. Hierdoor ontstaat er een prettiger visueel evenwicht en verbetert de leesbaarheid van je website voor bezoekers.

**Comment by Abeeryu** [comment]
Toegepast!
