### ISSUE TITLE
haal de slash voor "assets" weg in de img src zodat de afbeeldingen te zien zijn

### ISSUE THREAD

**Issue by Mossati** [Abeeryu/the-startup-responsive-interactieve-website#5]

**Comment by Abeeryu** [comment]
Thanks! ik heb het gedaan!

![Screenshot 2024-01-18 000228](https://github.com/Abeeryu/the-startup-responsive-interactieve-website/assets/144008500/26b062bc-3767-4a70-857c-4f2a423c8003)
