### ISSUE TITLE
voeg wat padding op de buttons zodat ze wat ruimte hebben

### ISSUE THREAD

**Issue by Mossati** [Abeeryu/the-startup-responsive-interactieve-website#7]

**Comment by Abeeryu** [comment]
Dankjewel voor je feedback! Het was wel handig en ik heb het toegepast! 👍 

![Screenshot 2024-01-17 113921](https://github.com/Abeeryu/the-startup-responsive-interactieve-website/assets/144008500/0698ba70-0fa9-40ab-94d8-03aa0932e9ae)
